### PR TITLE
test suite

### PR DESCRIPTION
**Pull request by enricofer**
I wrote a quick test suite mocking grib object and point_validity function.
I'm not sure to fully understand the module use and the units of the input parameters because from Routing test i'm getting a wrong result with an hour only isochrones and null path and position.
there is a fix to units.py where there is a wrong heading variable name
Could you have a look?

### CODE REVIEW

**Comment by dakk** [comment]
Thank you, I'll review the pull after Ester; I'm not sure why the Routing test fails, need further investigation. 
Does the mocked grib returns always the same value for same (lat,lon,time) pairs?

**Comment by enricofer** [comment]
The mocked grib does not depend from location, only from sample time. I don't find it very significant. Instead I would write a bit more smart point_of_validity func that could return a more complex response based on location (maybe a test against a predefined pattern of true false).   But If we find useful latitude and longitude could be included in random seeding to provide unique results for time, and location.

**Comment by dakk** [comment]
Ok, found the problem in your test; the "step" won't returns you always a path, but it calculates isochrones from the current point to the next; if it reaches the next waypoint it creates intermediate path, otherwise it continues to calculate isochrones from all intermediate isopoints. Check my commit on your repo and update the pull req

**Comment by enricofer** [comment]
I can't find any PR on my forked repo.

**Comment by dakk** [comment]
@enricofer you're right, it's here https://github.com/dakk/libweatherrouting/tree/enricofer/master

**Comment by enricofer** [comment]
Ok. now I see what you mean.

**Comment by dakk** [comment]
Step is implemented like this, so during calculation you have partial isochrones results for rendering

**Review by dakk — APPROVED** [review]

**Pull request merged**
